name: Update black IP list

on:
  push:
    branches: [ master ]
  
  workflow_dispatch:

  schedule: 
    - cron:  '10 12 * * *'

jobs:
  build:
    name: Generate black IP list
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Create dist folder
      run: mkdir -p dist

    - name: Obtain black IP lists
      run: curl -LR -o dist/ustcip.list "https://blackip.ustc.edu.cn/list.php?txt"

    - name: Generate black IP conf
      run: |
        CURRENT_DIR=$(pwd)
        cd dist
        sed '/:/d' ./ustcip.list > blackip4.conf
        cd $CURRENT_DIR

    - name: Set env variables
      run: |
        echo "RELEASE_NAME=$(date +%Y%m%d)" >> $GITHUB_ENV
        echo "TAG_NAME=$(date +%Y%m%d)" >> $GITHUB_ENV
      shell: bash

    - name: Push to release branch
      run: |
        mkdir publish
        cp -af dist/blackip4.conf publish/blackip4.conf
        cd publish
        git init
        git config --local user.name "${{ github.actor }}"
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git checkout -b release
        git add .
        git commit -m "${{ env.RELEASE_NAME }}"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin release
